environment:

  matrix:

    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.x"
      PIP: "C:\\Python34-x64\\Scripts\\pip"

platform: x64

before_script:
  - pip --version

install:
  - pip install codecov

build_script:
  - cmd: coverage run test.py
