environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: '2.7.x'
      PYTHON_ARCH: '64'

    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: '3.4.x'
      PYTHON_ARCH: '64'

build: off

install:
  - pip install codecov

test_script:
  - coverage run test.py
