environment:

  matrix:

    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.x"
      PIP: "C:\\Python34-x64\\Scripts\\pip3"

platform: x64

install:
  - pip3 --version
  - pip3 install codecov

build_script:
  - cmd: coverage run test.py
