environment:
  matrix:
    - PYTHON: "C:\\Python27_32"
      PYTHON_VERSION: '2.7'
    - PYTHON: "C:\\Python34_64"
      PYTHON_VERSION: '3.4'

install:
  - cmd: '%PIP3% install codecov'

build: false

test_script:
  - cmd: coverage run test.py"
