name: publish

# on:
#   release:
#     types: [created]

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Dependencies
        run: pip3 install wheel twine

      - name: Build Package
        run: python3 setup.py sdist bdist_wheel

      - name: Publish to PyPI
        run: twine upload dist/*
        env:
          TWINE_USERNAME: abranhe
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
